# Generated by Django 5.0.6 on 2024-09-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_shipping_address_cart_shipping_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shipping_zip',
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
