# Generated by Django 5.0.6 on 2024-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('honey', 'Honey'), ('beeswax', 'Beeswax'), ('pollen', 'Pollen'), ('propolis', 'Propolis')], default='honey', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
